# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9125b2ef5707f6509eb2432f152ff5d3349098bd3026dc16554382ad7fab59bc3fe6c7585eadfc664d2671de2477df78ccadd17661c1ec49786a793a9ec17063

test:
  secret_key_base: bcbef4e2907d81a6613946c4963981632c72a5c5868bd8c0b9b0bbe16512d09190a75792fbe5bb4bc66be555ffe00f0e22b5fbbb227f070f3239b1dd153b5575

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
